/**
 * @file    el_usbxch.c
 * @author  Carol Nasser
 * @brief   USB Vendor Class Bulk Exchange Driver for STM32F4.
 * @details Implements a dual-bulk-pair (2×IN + 2×OUT) USB transfer driver
 *          using the STM32 USB Device library (LL + HAL PCD layer). Data is
 *          buffered through `el_ring_t` ring buffers and transferred
 *          asynchronously via the USB ISR callbacks.
 *
 *          Endpoint map:
 *            EP0  – Control (standard)
 *            EP1  – Bulk OUT 0x01 / Bulk IN 0x81
 *
 *          The USB Device stack (USBD_HandleTypeDef) and the lower-level PCD
 *          handle (hpcd_USB_OTG_FS) are expected to be provided by the
 *          STM32CubeMX-generated middleware.
 */

#include "el_usbxch.h"    
#include "stm32f4xx_ll_rcc.h"
#include "stm32f4xx_ll_gpio.h"
#include <string.h>
#include "usb_device.h"

#ifdef EL_USBXCH_ENABLED

/* ---------------------------------------------------------------------------
 * External references – these symbols are defined by the STM32Cube USB device
 * stack (usbd_conf.c / usbd_desc.c).  The user must ensure MX_USB_DEVICE_Init()
 * has been called before (or inside) el_usbxch_init().
 * ---------------------------------------------------------------------------
 * 
 * If your project does not use MX_USB_DEVICE_Init, you must still provide:
 *   - USBD_HandleTypeDef  hUsbDeviceFS;
 *   - PCD_HandleTypeDef   hpcd_USB_OTG_FS;
 * and initialise them before calling el_usbxch_init().
 *
 * We declare them here as `extern` so they can be located in user code
 * (e.g. usbd_conf.c or main.c generated by CubeMX).
 */


/* ---------------------------------------------------------------------------
 * Internal forward declarations
 * --------------------------------------------------------------------------- */
static void usbxch_start_tx(el_usbxch_handle_t *h);
/* ---------------------------------------------------------------------------
 * Handle singleton for callback dispatch
 * ---------------------------------------------------------------------------
 * The USB stack callbacks (received from PCD / USBD layer) carry only the
 * endpoint address; we need a way to reach the handle.  Because the driver
 * is typically used as a single instance, we keep a static pointer.
 * For multi-instance support, extend with a lookup table keyed by itf.
 */

/* ===========================================================================
 * Public API
 * =========================================================================== */

void el_usbxch_init(el_usbxch_handle_t *h)
{
    /* --- Clear the handle --- */
    memset(h, 0, sizeof(*h));
    /* --- Initialise ring buffers --- */
    el_ring_init(&h->tx, h->tx_storage, sizeof(h->tx_storage));
    el_ring_init(&h->rx, h->rx_storage, sizeof(h->rx_storage));
    h->usbxch.ctx = h;
    hUsbDeviceFS.pClassData = (void*)&h->usbxch;
    MX_USB_DEVICE_Init();
}

/* ---------------------------------------------------------------------------
 * Write
 * --------------------------------------------------------------------------- */
uint32_t el_usbxch_write(el_usbxch_handle_t *h, const uint8_t *data, uint32_t length)
{
    void *w1, *w2;
    uint16_t c1, c2;
    if (el_ring_write_reserve(&h->tx, (uint16_t)length, &w1, &c1, &w2, &c2)) {
        memcpy(w1, data, c1);
        if(w2)memcpy(w2, data + c1, c2);
        el_ring_write_commit(&h->tx, length);
    } else {
        return length;
    }
    return 0;
}

/* ---------------------------------------------------------------------------
 * Write available (space left in tx buffer)
 * --------------------------------------------------------------------------- */
uint32_t el_usbxch_write_available(el_usbxch_handle_t *h)
{
    return (uint32_t)el_ring_free(&h->tx);
}

/* ---------------------------------------------------------------------------
 * Flush – trigger an IN transfer immediately if data is pending
 * --------------------------------------------------------------------------- */
uint32_t el_usbxch_flush(el_usbxch_handle_t *h)
{
    if (h->flags & USBXCH_FLAG_TX_BUSY)
        return 1; /* already in progress */

    usbxch_start_tx(h);
    return 0;
}


/* ---------------------------------------------------------------------------
 * Clear – drain all ring buffers and reset stats
 * --------------------------------------------------------------------------- */
uint32_t el_usbxch_clear(el_usbxch_handle_t *h)
{
    /* Drain TX: reset head/tail to empty */
    h->tx.head = h->tx.tail = 0;
    h->rx.head = h->rx.tail = 0;
    return 0;
}

/* ---------------------------------------------------------------------------
 * Read from OUT endpoint 1
 * --------------------------------------------------------------------------- */
uint32_t el_usbxch_read(el_usbxch_handle_t *h, uint8_t *data, uint32_t length)
{
    void *r1, *r2;
    uint16_t c1, c2;
    uint32_t total = 0;
    if (el_ring_read_reserve(&h->rx, &r1, &c1, &r2, &c2)) {
        uint16_t to_copy = (uint16_t)((length < (uint32_t)(c1 + c2)) ? length : (uint32_t)(c1 + c2));

        uint16_t copy_from_first = (to_copy < c1) ? to_copy : c1;
        memcpy(data, r1, copy_from_first);
        total += copy_from_first;

        if (total < length && r2) {
            uint16_t rem = (uint16_t)(length - total);
            uint16_t copy_from_second = (rem < c2) ? rem : c2;
            memcpy(data + copy_from_first, r2, copy_from_second);
            total += copy_from_second;
        }
        el_ring_read_commit(&h->rx, (uint16_t)total);
    }
    return total;
}

/* ---------------------------------------------------------------------------
 * Read available (occupied bytes in RX ring)
 * --------------------------------------------------------------------------- */
uint32_t el_usbxch_read_available(el_usbxch_handle_t *h)
{
    uint16_t occ = el_ring_size(&h->rx);
    return occ;
}

/* ---------------------------------------------------------------------------
 * Connected status – true when VBUS present and SET_CONFIGURATION received
 * --------------------------------------------------------------------------- */
bool el_usbxch_connected(el_usbxch_handle_t *h)
{
    return (h->flags & USBXCH_FLAG_CONFIGURED) != 0;
}

/* ---------------------------------------------------------------------------
 * Update – periodic housekeeping (call from main/super-loop)
 * --------------------------------------------------------------------------- */
void el_usbxch_update(el_usbxch_handle_t *h)
{
    /* Start IN transfer for EP1 if data is pending */
    if (!(h->flags & USBXCH_FLAG_TX_BUSY) && el_ring_size(&h->tx) > 0)
        usbxch_start_tx(h);
}

/* ===========================================================================
 * Internal helpers
 * =========================================================================== */

/**
 * @brief  Kick-start an IN (device-to-host) transfer on the given endpoint.
 * @note   Called from thread context (update / write) – safe with IRQs enabled.
 *         The actual HAL_PCD_EP_Transmit() can be called with IRQs enabled;
 *         it will raise an interrupt on completion.
 */
static void usbxch_start_tx(el_usbxch_handle_t *h)
{
    el_ring_t *tx;
    uint8_t  busy_flag;

    tx       = &h->tx;
    busy_flag = USBXCH_FLAG_TX_BUSY;

    void *r1, *r2;
    uint16_t c1, c2;
    if (h->flags & busy_flag) {
        return;
    }

    if (!el_ring_read_reserve(tx, &r1, &c1, &r2, &c2)) {
        /* Nothing to send */
        return;
    }
    USBD_XCH_Transmit(&hUsbDeviceFS, r1, c1);
    h->tx_to_release = c1;
    h->flags |= busy_flag;
}


void USBD_XCH_GetRxStorage(void *ctx, uint8_t **ptr, uint16_t *size)
{
    el_usbxch_handle_t *h = ctx;
    void *r2;
    uint16_t c2;
    uint16_t fs = el_ring_free(&h->rx);
    el_ring_write_reserve(&h->rx, fs, &h->r1, &h->c1, &r2, &c2);
    *ptr = h->r1;
    *size = h->c1;
}

void USBD_XCH_RxComplete(void *ctx, uint8_t *rx_buf, uint16_t size)
{
    el_usbxch_handle_t *h = ctx;
    el_ring_write_commit(&h->rx, size);
}

void USBD_XCH_TxComplete(void *ctx)
{
    el_usbxch_handle_t *h = ctx;
    el_ring_read_commit(&h->tx, h->tx_to_release);

    void *r1, *r2;
    uint16_t c1, c2;
    if (!el_ring_read_reserve(&h->tx, &r1, &c1, &r2, &c2)) {
        /* Nothing to send */
        h->flags &= ~USBXCH_FLAG_TX_BUSY; //clear busy flag and return, nothing to send
        return;
    }
    USBD_XCH_Transmit(&hUsbDeviceFS, r1, c1);
    h->tx_to_release = c1;
}

#endif /* EL_USBXCH_ENABLED */